table DADOS_ATIVIDADE
	lineageTag: 436c15a7-7e5c-4eeb-b3e3-104860d3b6b0

	column Column1
		dataType: string
		lineageTag: ea125038-bd5a-4072-aaa3-2f1829a49995
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 1175cc51-7e51-4251-87bc-e398f4a274ea
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 0b7113ed-f20b-464b-bc52-7314fd90769b
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 807a8b02-4947-45c6-8b01-aae251cafc77
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 3b5a20a2-d407-4def-a2e9-006ba1065784
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: 18d2b498-ceda-463d-a1e4-17b051fd0515
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: 8559ed34-5925-46c4-b3ab-bcd4c30cc5b2
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: cf10da10-d7ff-42d3-a414-2370a5d440d6
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: 960a8583-0baa-4889-ba1d-ef07292ce853
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: 206d2969-d1f4-4a57-8dab-f11000ba90f0
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: d8ba5ead-b768-487d-a14b-e02be334f4aa
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: 38446130-90e6-4e02-9d6a-7d4f1b9cf78d
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		lineageTag: 9ba530f0-b492-431e-a32b-f0dff4a60d00
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		lineageTag: ea857849-4764-4a7d-909f-83f284646bcb
		summarizeBy: none
		sourceColumn: Column14

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: f3593eb2-4826-4815-b6e1-77b4d2b1d85f
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	column Column16
		dataType: string
		lineageTag: 95888dcf-cd5c-445f-abbc-1ba97b76e9f4
		summarizeBy: none
		sourceColumn: Column16

		annotation SummarizationSetBy = Automatic

	column Column17
		dataType: string
		lineageTag: 7c753579-bb54-44cb-9eeb-f05fb07e3eb5
		summarizeBy: none
		sourceColumn: Column17

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		lineageTag: 901372f5-f81a-4c1b-8454-5a964439f088
		summarizeBy: none
		sourceColumn: Column18

		annotation SummarizationSetBy = Automatic

	column Column19
		dataType: string
		lineageTag: 013707a6-b210-4284-bac9-d42fd2051349
		summarizeBy: none
		sourceColumn: Column19

		annotation SummarizationSetBy = Automatic

	column Column20
		dataType: string
		lineageTag: 3e59463a-a664-4967-8bdd-807b438ac5c8
		summarizeBy: none
		sourceColumn: Column20

		annotation SummarizationSetBy = Automatic

	column Column21
		dataType: string
		lineageTag: ee57bfe7-4a25-47e5-ad20-88d561ef10f7
		summarizeBy: none
		sourceColumn: Column21

		annotation SummarizationSetBy = Automatic

	column Column22
		dataType: string
		lineageTag: a3c2450e-50e3-49e2-8cda-5577f1a1b3f1
		summarizeBy: none
		sourceColumn: Column22

		annotation SummarizationSetBy = Automatic

	column Column23
		dataType: string
		lineageTag: b17462b9-117c-4500-8ad6-ad020b44edbb
		summarizeBy: none
		sourceColumn: Column23

		annotation SummarizationSetBy = Automatic

	column Column24
		dataType: string
		lineageTag: 7c314bd5-d59b-4f53-be55-c409b71ed50b
		summarizeBy: none
		sourceColumn: Column24

		annotation SummarizationSetBy = Automatic

	partition DADOS_ATIVIDADE = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\berna\Downloads\DADOS_ATIVIDADE.csv"),[Delimiter=",", Columns=24, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

